# Generated by Django 4.2.1 on 2023-05-14 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DomainNameHelper",
        ),
    ]
