# Generated by Django 4.2.1 on 2023-05-20 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0002_delete_domainnamehelper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
