# Generated by Django 4.2.1 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0003_alter_zone_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="is_delegate",
            field=models.BooleanField(default=False),
        ),
    ]
