# Generated by Django 4.2.4 on 2023-10-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0004_zone_is_delegate"),
    ]

    operations = [
        migrations.AddField(
            model_name="zoneapikey",
            name="name",
            field=models.CharField(default="", editable=False, max_length=253),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ManagedDomainName",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False,
                        max_length=253,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_challenge_response", models.CharField(blank=True, max_length=64)),
                ("new_challenge_response", models.CharField(blank=True, max_length=64)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="domains.zone",
                    ),
                ),
            ],
        ),
    ]
